# Generated by Django 5.1.5 on 2025-02-04 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restorants', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DishOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restorants.dish')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('Uber', 'Uber'), ('Uklon', 'Uklon')], max_length=50)),
                ('status', models.CharField(choices=[('ready', 'Ready'), ('finished', 'Finished'), ('in_progress', 'In Progress')], default='in_progress', max_length=50)),
                ('addresses', models.TextField()),
                ('external_order_id', models.CharField(max_length=100, unique=True)),
                ('dish_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='orders.dishorder')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_order_id', models.CharField(max_length=100, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dish_orders', to='users.user')),
            ],
        ),
        migrations.AddField(
            model_name='dishorder',
            name='dish_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_dishes', to='orders.order'),
        ),
    ]
